name: Copy Files Pipeline

on:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        
      - name: Copy files from source to destination
        run: |
          echo "Starting copy..."

          SOURCE="/home/soumitri.mishra@apmosys.mahape/Downloads/git-cheat-sheet-education.pdf"
          DESTINATION="/home/soumitri.mishra@apmosys.mahape/Documents"

          cp $SOURCE $DESTINATION

          echo "Copied"
