name: Copy Files Pipeline

on:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: self-hosted

    steps:
      - name: Copy files from source to destination
        run: |
          echo "Starting copy..."

          SOURCE="/home/soumitri.mishra@apmosys.mahape/Downloads/TC_01 (3).xlsx"
          DESTINATION="/home/soumitri.mishra@apmosys.mahape/Documents"

          cp $SOURCE $DESTINATION

          echo "Copied"
